version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME}
      - UMASK_SET=${UMASK} 
    volumes:
      - ${CONFIG}/bazarr:/config
      - ${DATA}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
