version: "2.1"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ:${TIME}
      - WEBPASSWORD:${PASS}
    volumes:
      - ${CONFIG}/pihole/etc-pihole/:/etc/pihole/
      - ${CONFIG}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 1.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    logging:
      driver: none

