version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME}
      - UMASK_SET=${UMASK}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DATA}:/data
    ports:
      - 8989:8989
    logging:
      driver: none
