version: "2.1"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=${PUID2}
      - PGID=${PGID2}
      - TZ=${TIME}
      - UMASK_SET=${UMASK}
    volumes:
      - ${CONFIG}/syncthing:/config
      - ${SYNC}:/sync
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
